db:
  host: 'ec2-34-192-173-173.compute-1.amazonaws.com'
  database: 'd90rv575ns292m'
  username: 'gmwqnwjpjrxtiq'
  password: 'aaacc8ee26376d2ed0a9012167e7a64a7c58ab21c9ea6383ab7a507ab0861539'
  synchronize: true

jwt:
  secret: 'vySecret'
